//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Dispatcher.refWsSms {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSmsSoap", Namespace="http://efficom.org/")]
    public partial class WebServiceSms : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private AuthentificationEnteteSoap authentificationEnteteSoapValueField;
        
        private System.Threading.SendOrPostCallback envoyerSmsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceSms() {
            this.Url = global::Dispatcher.Properties.Settings.Default.Dispatcher_refWsSms_WebServiceSms;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthentificationEnteteSoap AuthentificationEnteteSoapValue {
            get {
                return this.authentificationEnteteSoapValueField;
            }
            set {
                this.authentificationEnteteSoapValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event envoyerSmsCompletedEventHandler envoyerSmsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://efficom.org/Test", RequestNamespace="http://efficom.org/", ResponseNamespace="http://efficom.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test() {
            object[] results = this.Invoke("Test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        /// <remarks/>
        public void TestAsync(object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[0], this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthentificationEnteteSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://efficom.org/envoyerSms", RequestNamespace="http://efficom.org/", ResponseNamespace="http://efficom.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string envoyerSms(Sms sms) {
            object[] results = this.Invoke("envoyerSms", new object[] {
                        sms});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void envoyerSmsAsync(Sms sms) {
            this.envoyerSmsAsync(sms, null);
        }
        
        /// <remarks/>
        public void envoyerSmsAsync(Sms sms, object userState) {
            if ((this.envoyerSmsOperationCompleted == null)) {
                this.envoyerSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenvoyerSmsOperationCompleted);
            }
            this.InvokeAsync("envoyerSms", new object[] {
                        sms}, this.envoyerSmsOperationCompleted, userState);
        }
        
        private void OnenvoyerSmsOperationCompleted(object arg) {
            if ((this.envoyerSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.envoyerSmsCompleted(this, new envoyerSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://efficom.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://efficom.org/", IsNullable=false)]
    public partial class AuthentificationEnteteSoap : System.Web.Services.Protocols.SoapHeader {
        
        private Utilisateur userField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public Utilisateur user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://efficom.org/")]
    public partial class Utilisateur {
        
        private int idUserField;
        
        private string loginField;
        
        private string passwordField;
        
        private string nomExpediteurField;
        
        /// <remarks/>
        public int IdUser {
            get {
                return this.idUserField;
            }
            set {
                this.idUserField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string NomExpediteur {
            get {
                return this.nomExpediteurField;
            }
            set {
                this.nomExpediteurField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://efficom.org/")]
    public partial class Sms {
        
        private int idSmsField;
        
        private string numDestinataireField;
        
        private string textMessageField;
        
        private int aEnvoyerField;
        
        private int etatMessageField;
        
        private int fkUserField;
        
        private System.DateTime dateEnvoiField;
        
        /// <remarks/>
        public int IdSms {
            get {
                return this.idSmsField;
            }
            set {
                this.idSmsField = value;
            }
        }
        
        /// <remarks/>
        public string NumDestinataire {
            get {
                return this.numDestinataireField;
            }
            set {
                this.numDestinataireField = value;
            }
        }
        
        /// <remarks/>
        public string TextMessage {
            get {
                return this.textMessageField;
            }
            set {
                this.textMessageField = value;
            }
        }
        
        /// <remarks/>
        public int AEnvoyer {
            get {
                return this.aEnvoyerField;
            }
            set {
                this.aEnvoyerField = value;
            }
        }
        
        /// <remarks/>
        public int EtatMessage {
            get {
                return this.etatMessageField;
            }
            set {
                this.etatMessageField = value;
            }
        }
        
        /// <remarks/>
        public int FkUser {
            get {
                return this.fkUserField;
            }
            set {
                this.fkUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateEnvoi {
            get {
                return this.dateEnvoiField;
            }
            set {
                this.dateEnvoiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void envoyerSmsCompletedEventHandler(object sender, envoyerSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class envoyerSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal envoyerSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591